name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Compile Java files
      run: |
        javac -cp . "java Folder/hello.java"
        javac -cp . "src/com/filenest/FileOrganizer.java"
        
    - name: Run basic tests
      run: |
        java -cp "java Folder" hello
        echo "FileOrganizer compilation successful"